name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Thank you for opening an issue! We appreciate your contribution and will get back to you as soon as possible."
          pr-message: "Thank you for submitting a pull request! We appreciate your help in making this project better and will review your request as soon as possible."
